version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: database
    networks:
      - my_network
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build:
      context: . #path to the docker file
      target: production #here we're refering to the stage in dockerfile
    container_name: server
    networks:
      - my_network
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge