version: '3.9'

services:
  api:
    build: 
      context: .
      target: development
    #container_name: server
    networks:
      - my_network
    volumes:
      - ./:/user/src/app
      - /user/src/app/node_modules
    env_file:
      - .env
    #ports:
    #  - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run dev

  db:
    image: postgres:latest
    container_name: database
    networks:
      - my_network
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - my_network
    depends_on:
      - api
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge