version: '3.9'

services:
  api:
    build: 
      context: .
      target: development
    container_name: server
    volumes:
      - ./:/user/src/app
      - /user/src/app/node_modules
    env_file:
      - .env
    ports:
      - 8000:8000
    command: npm run dev

  db:
    image: postgres:latest
    container_name: database
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_DB: docker-rent
      POSTGRES_PASSWORD: docker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    